--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/MineShop
build-by-default: true
branches:
- main
projects:
  MineShop:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
      - src: jojoe77777/FormAPI/libFormAPI
        branch: master
        version: ^2.1.1
...
