--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/MineShop
build-by-default: true
branches:
- main
projects:
  MineShop:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.5
      - src: jojoe77777/FormAPI/FormAPI
        branch: master
        version: ^2.1.1
      - src: kim/present/utils/itemserialize
        branch: main
        version: ^2.0.0
...
