name: MineShop
main: angga7togk\mineshop\MineShop
api: 5.3.0
author: Angga7togk
version: 1.0.0
description: Shop with Ore Economy
virions: ["InvMenu", "libFormAPI"]

permissions:
  mineshop.command:
    default: true
    description: Allows to use /mineshop command
  mineshop.command.add:
    default: op
    description: Allows to use /mineshop add command
  mineshop.command.delete:
    default: op
    description: Allows to use /mineshop delete command